#!/usr/bin/env python3
"""
Generate the seven preview pages.

The chrome — unofficial ribbon, brand bar, the city's own nav, the sub-nav across
these previews, footer — is identical on every page, and having edited it once by
hand across several files already, it lives here instead. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "hub":      "HCHCA8lwePKxAf6EXfIB3H",   # both centers, every program
    "clarke":   "bgGoKLrxK8AcpRaiffiEyG",   # Clarke, with a Pools filter
    "larkey":   "09tWnBhjtxeUm8scApEWFQ",   # Larkey, month at a time
    "bays":     "EHMWrlAQ2CfgWIKRBXKQAC",   # the three wading-pool teaching bays
    "masters":  "BA51EP0QyGuJFUr3YTLK4e",   # Walnut Creek Masters only
    "pool25":   "EJycPnzHYwjOEQFFYkpMlI",   # the 25-meter pool only
}

NAV = [
    ("index.html",     "Aquatics"),
    ("clarke.html",    "Clarke Memorial"),
    ("larkey.html",    "Larkey"),
    ("aquabears.html", "Aquabears"),
    ("masters.html",   "Masters"),
    ("aquanuts.html",  "Aquanuts"),
    ("wcsc.html",      "Swim Club"),
]


def cal(key, title, short=False, caption=""):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    cls = "cal short" if short else "cal"
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="{cls}">
    <iframe src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a City of Walnut Creek website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@600;700&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a City of Walnut Creek page. A replica of the
  <a href="https://www.walnutcreekartsrec.org/aquatics" target="_blank" rel="noopener">Walnut Creek Arts&nbsp;+&nbsp;Rec aquatics pages</a>
  with live <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html"><span class="city">WALNUT CREEK</span>ARTS <span class="plus">+</span> REC</a>
    <div class="tel">Front desk (925)&nbsp;943-5859 &middot; aquatics@walnut-creek.org</div>
  </div>
</header>

<nav class="main">
  <ul>
    <li><a href="https://www.walnutcreekartsrec.org/programs-activities" target="_blank" rel="noopener">Programs + Activities</a></li>
    <li><a href="https://www.walnutcreekartsrec.org/parks-facilities" target="_blank" rel="noopener">Parks + Facilities</a></li>
    <li class="on"><a href="index.html">Aquatics</a></li>
    <li><a href="https://www.walnutcreekartsrec.org/seniors" target="_blank" rel="noopener">Seniors</a></li>
    <li><a href="https://www.walnutcreekartsrec.org/about" target="_blank" rel="noopener">About</a></li>
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what the Walnut Creek aquatics pages would
    look like with a live calendar on each one. Not affiliated with the City of Walnut Creek.</p>
    <p>Schedules transcribed 16 September 2026 from walnutcreekartsrec.org, the city's PerfectMind
    registration system, and swim4wc.org. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


# ── The findings block, shared by the hub and Clarke ───────────────────────────
QUESTIONS = """<section class="wrap">
  <h2>Questions for the aquatics office</h2>
  <p>Everything here was transcribed from what Walnut Creek publishes. These are the places where the
  published sources disagree, go quiet, or where we had to make a call &mdash; each one is marked on
  the calendar entry itself.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Evening lap swim: Monday&ndash;Thursday, or Monday&ndash;Friday?</div>
      <div class="a">The <em>Current Lap Swim Hours</em> box says Mon&ndash;Thu 7&ndash;8pm. The
      lane-allocation table directly below it says Mon&ndash;Friday for the same band. Entered as
      Mon&ndash;Thu.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Guppy and Seal are booked into the same lane at 5:10pm</div>
      <div class="a">Class #85243 (Guppy) and #85260 (Seal) are both recorded on <em>50m Lane 01</em>,
      Tuesdays and Thursdays at 5:10, across all four session dates. That is the registration system's
      own data. Which one is actually in Lane 1?</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>Saturday 11:00 &mdash; lessons or lap swim on Lanes 1&ndash;2?</div>
      <div class="a">The allocation table hands lanes 1&ndash;14 to lap swim from 11:00 on weekends,
      while a Saturday Guppy class and two private lessons sit on Lanes 1 and 2. Pool Relay suggests
      shifting lap swim to lanes 3&ndash;16, which is presumably what happens on deck &mdash; the page
      never says so.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>How many lanes does Masters actually get?</div>
      <div class="a">The team publishes times but never lanes. We entered 12 &mdash; the balance of the
      20-lane short course after the city's published public allocation. It closes perfectly in every
      weekday band, but the Saturday 9:30&ndash;10:45 practice has no published allocation to bound it
      at all.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Is water exercise running?</div>
      <div class="a">The page lists Tue/Wed/Thu at 8:15 (shallow) and 9:15 (deep), then says
      <em>&ldquo;unfortunately we do not have an instructor at this time.&rdquo;</em> Those slots are
      deliberately <strong>not</strong> on the calendar &mdash; an event holds water no matter what its
      description says. Is the water still reserved, or released to lap swim?</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Where do three of the four teams train?</div>
      <div class="a">Only Masters publishes practice times. The Aquabears, the Aquanuts and the summer
      Swim Club occupy real water on a real schedule that nothing public describes &mdash; see their
      pages above.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Weekend recreational swim &mdash; still running, and in which pool?</div>
      <div class="a">The page lists recreational swim under both the 50-meter and the 25-meter pool.
      We put it in the 25-meter pool, because the allocation table already commits 14 of the 20
      short-course lanes to lap swim at that hour.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>When do Larkey's weekday sprayground hours run?</div>
      <div class="a">The $3 sprayground-only hours (Mon&ndash;Thu, 10:30&ndash;12:30 and
      4:30&ndash;6:30) are published without dates. We used the Memorial Day&ndash;Labor Day season the
      swim pass names, stopping before Labor Day itself &mdash; the center was weekends-only by
      September.</div>
    </li>
  </ul>
</section>

"""

LANE_TABLE = """  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Time</th><th>Public lap swim</th><th>Masters</th><th>The 20-lane pool</th></tr></thead>
    <tbody>
      <tr><td>5:30 &ndash; 8:00 am</td><td class="n">8</td><td class="n">12</td><td class="n">20</td></tr>
      <tr><td>8:00 &ndash; 10:30 am</td><td class="n">20</td><td class="n">&mdash;</td><td class="n">20</td></tr>
      <tr><td>10:30 am &ndash; 1:00 pm</td><td class="n">8</td><td class="n">12</td><td class="n">20</td></tr>
      <tr><td>1:00 &ndash; 4:00 pm</td><td class="n">14</td><td class="n">&mdash;</td><td class="n">20</td></tr>
      <tr><td>7:00 &ndash; 8:00 pm</td><td class="n">8</td><td class="n">12</td><td class="n">20</td></tr>
    </tbody>
  </table>
  </div>
"""

BAY_TABLE = """  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Bay or lane</th><th>Levels taught there</th><th>Tue &amp; Thu start times</th></tr></thead>
    <tbody>
      <tr><td>Wading &mdash; East</td><td>Level 2 Starfish</td><td>4:30 &middot; 5:50 &middot; 6:30</td></tr>
      <tr><td>Wading &mdash; Middle</td><td>Level 3 Seahorse</td><td>4:30 &middot; 5:50</td></tr>
      <tr><td>Wading &mdash; West</td><td>Level 4 Lobster</td><td>4:30 &middot; 5:10 &middot; 5:50 &middot; 6:30</td></tr>
      <tr><td>50m Lane 1</td><td>Level 1 Guppy, Level 5 Seal, Level 6 Dolphin</td><td>5:10 &middot; 6:30</td></tr>
      <tr><td>50m Lane 2</td><td>Private lessons</td><td>4:30 &middot; 5:05 &middot; 5:40 &middot; 6:15</td></tr>
    </tbody>
  </table>
  </div>
"""


# ══ 1. The hub ════════════════════════════════════════════════════════════════
HUB = f"""<section class="wrap hero">
  <div class="crumb">Aquatics</div>
  <h1>Aquatics</h1>
  <p class="kicker">Both swim centers &middot; every program &middot; this week</p>
  <p class="lead">Lap swim, lessons, Masters, recreational swim, rentals and the sprayground &mdash;
  at Clarke Memorial and at Larkey, on one calendar. Use the <strong>Facilities</strong> menu to narrow
  to one center, or leave it on <strong>All</strong>.</p>

{cal("hub", "Walnut Creek Aquatics — everything, both swim centers",
     caption="Larkey is closed until Memorial Day, so this week is all Clarke.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Six links, one ordinary question</h2>
    <p class="q">&ldquo;Can my seven-year-old have a swim lesson at a time when I can also swim laps?&rdquo;</p>
    <p style="margin:0 0 14px">On the published page, answering that means leaving it. Here is the
    actual trail:</p>
    <ol>
      <li>Open <b>Clarke Memorial</b> and read the lap-swim lane table. <i>Lap swim, got it.</i></li>
      <li>Back. Open <b>Swim Lessons and Classes</b> &mdash; level descriptions, but no times.</li>
      <li>Follow <b>Group Lessons</b> out to the registration system. A second website.</li>
      <li>Expand <b>each of the seven levels</b> one at a time to see which have sessions. Seven more clicks.</li>
      <li>Back out and open <b>Private Swim Lessons</b> &mdash; a separate calendar again.</li>
      <li>Remember the pool also has a Masters team in it. Open <b>Swim Teams</b>, then the team's own
          site, then its <b>Practice Times</b> page. A third and a fourth website.</li>
    </ol>
    <p class="answer"><b>Four websites and about a dozen clicks</b> &mdash; and at the end you are
    holding four separate schedules in your head and comparing them yourself. The calendar above
    answers the same question by looking at Tuesday.</p>
  </div>
</div>

<section class="wrap">
  <h2>Swim Centers</h2>
  <div class="cards pair">
    <a class="card" href="larkey.html">
      <div class="pic"></div>
      <div class="body">
        <h3>Larkey Park</h3>
        <p>This pool and spray ground are open during the summer.</p>
        <div class="already">Already above: closed until Memorial Day</div>
      </div>
    </a>
    <a class="card" href="clarke.html">
      <div class="pic b"></div>
      <div class="body">
        <h3>Clarke Memorial</h3>
        <p>Enjoy three outdoor swimming pools located in Heather Farm Park.</p>
        <div class="already">Already above: all three pools, all week</div>
      </div>
    </a>
  </div>

  <h2 style="margin-top:38px">Programs and Rentals</h2>
  <div class="cards">
    <a class="card" href="clarke.html#lessons">
      <div class="pic c"></div>
      <div class="body">
        <h3>Swim Lessons and Classes</h3>
        <p>Seasonal options align with quarterly registration windows.</p>
        <div class="already">Already above: every level, with its bay and lane</div>
      </div>
    </a>
    <a class="card" href="clarke.html#rentals">
      <div class="pic d"></div>
      <div class="body">
        <h3>Pool Rentals</h3>
        <p>Dive into the ultimate celebration with our poolside picnic rentals!</p>
        <div class="already">Already above: which weekends are bookable</div>
      </div>
    </a>
    <a class="card" href="masters.html">
      <div class="pic e"></div>
      <div class="body">
        <h3>Swim Teams</h3>
        <p>Walnut Creek Aquatics is proud to be home to four wonderful teams.</p>
        <div class="already">Already above: Masters, in the water beside you</div>
      </div>
    </a>
    <a class="card" href="larkey.html#passes">
      <div class="pic f"></div>
      <div class="body">
        <h3>Summer Recreational Swim Passes</h3>
        <p>Access the pools and spray ground during rec swim hours.</p>
        <div class="already">Already above: the hours the pass buys</div>
      </div>
    </a>
  </div>
  <p class="capt" style="margin-top:18px">These are exactly the six cards on the published page.
  Nothing has been taken away &mdash; the calendar just means you no longer have to open them all in
  order to plan a Tuesday.</p>

  <h2 style="margin-top:38px">The four teams</h2>
  <div class="cards">
    <a class="card" href="aquabears.html">
      <div class="pic g"></div>
      <div class="body"><h3>Aquabears</h3>
      <p>Year-round USA Swimming age-group team. Eight practice groups.</p></div>
    </a>
    <a class="card" href="masters.html">
      <div class="pic h"></div>
      <div class="body"><h3>Masters</h3>
      <p>Adults 19&ndash;90, competitive and fitness. Thirteen practices a week.</p></div>
    </a>
    <a class="card" href="aquanuts.html">
      <div class="pic i"></div>
      <div class="body"><h3>Aquanuts</h3>
      <p>Synchronized swimming, year round. Home of Olympic champions.</p></div>
    </a>
    <a class="card" href="wcsc.html">
      <div class="pic j"></div>
      <div class="body"><h3>Walnut Creek Swim Club</h3>
      <p>Summer recreational swim team, in its 55th year.</p></div>
    </a>
  </div>
</section>

<section class="wrap">
  <h2>What one calendar knows that six links cannot</h2>

  <h3>1. The other twelve lanes</h3>
  <p>Walnut Creek publishes lap swim as a <em>table of lane counts</em>. It never says what the rest of
  the pool is doing, because the city does not run it: the Masters team publishes its own practice
  times, on its own website. Put both on one calendar and the arithmetic closes exactly.</p>
{LANE_TABLE}
  <p class="capt">The 8:00&ndash;10:30 block, where Masters is out of the water, is the one time all
  twenty lanes are yours. No published page says that today.</p>

  <h3 style="margin-top:30px">2. Which water a lesson is actually in</h3>
  <p>The wading pool runs three teaching bays side by side. The city's registration system knows which
  bay each class uses; the aquatics page has never had anywhere to say so.</p>
{BAY_TABLE}

  <h3 style="margin-top:30px">3. That a season ends on a date</h3>
  <p>Larkey closed after Labor Day and its calendar closed with it, because the season was entered as
  dates rather than as a sentence. Nobody has to go back in September and edit
  <em>&ldquo;open weekends only through 9/7&rdquo;</em> off a web page, and nobody has to retype the
  summer next May.</p>
</section>

{QUESTIONS}<section class="wrap">
  <h2>Contact</h2>
  <p>Arts + Recreation Customer Service Central: (925) 295-1490<br>
  Front Desk: (925) 943-5859<br>
  <a href="mailto:artsrec@walnut-creek.org">artsrec@walnut-creek.org</a></p>
</section>

"""

# ══ 2. Clarke Memorial ════════════════════════════════════════════════════════
CLARKE = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Swim Centers</div>
  <h1>Clarke Memorial Swim Center</h1>
  <p class="kicker">Open year round &middot; three pools &middot; Heather Farm Park</p>
  <p class="lead">A 50-meter heated pool open all year, a 25-meter pool with a diving board, and a
  heated wading pool. 1750 Heather Dr, Walnut Creek. Front desk (925)&nbsp;943-5859.</p>

{cal("clarke", "Clarke Memorial Swim Center — this week",
     caption="Use the <strong>Pools</strong> menu to move between the 50-meter, 25-meter and wading pools.")}

  <h2>The three pools</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Pool</th><th>Season</th><th>What runs in it</th></tr></thead>
    <tbody>
      <tr><td>50-meter, heated</td><td>Year round</td><td>Adult lap swim (13+), water exercise, recreational swim, swim lessons, Masters</td></tr>
      <tr><td>25-meter, with a 1-meter board</td><td>Summer for lessons and rec swim</td><td>Year round for Aquanuts synchronized swim practice</td></tr>
      <tr><td>Wading pool, 3 feet, heated</td><td>Spring, summer and fall</td><td>Swim lessons, in three bays &mdash; East, Middle and West</td></tr>
    </tbody>
  </table>
  </div>
</section>

<div class="trail">
  <div class="wrap">
    <h2>The lane table, and the twelve lanes it cannot see</h2>
    <p>Walnut Creek does something unusual and genuinely useful: it publishes lap swim as a
    <b>table of lane counts</b> rather than as opening hours &mdash; 8 lanes, then 20, then 8, then 14.
    That answers <i>&ldquo;how many lanes do I get?&rdquo;</i> and nothing else.</p>
    <p>It cannot say what the other twelve lanes are doing, because <b>the city does not run them</b>.
    The Masters team publishes its own practice times, on its own website, in a different system
    entirely. Put both on one calendar and the arithmetic closes exactly, band after band.</p>
    <p class="answer">Two independent sources reconciling to exactly twenty is far better evidence than
    either one alone &mdash; and <b>a swimmer can finally see that 8:00&ndash;10:30 is the one window
    when the whole pool is public.</b></p>
  </div>
</div>

<section class="wrap">
  <h2>Adult lap swim</h2>
  <p>Ages 13+, $8 drop-in. Circle swimming is enforced and instruction of any kind is prohibited.
  Monthly and yearly passes are available.</p>
{LANE_TABLE}
  <p class="capt">Weekends run 11:00&nbsp;am&ndash;4:00&nbsp;pm with 14 lanes. The Masters column is
  ours, not the city's &mdash; see the questions at the foot of this page.</p>
</section>

<section class="wrap" id="lessons">
  <h2>Swim lessons</h2>
  <p>Ten levels from Guppy (6 months, parent in the water) through Shark, plus Adult &amp; Teen,
  adaptive-needs lessons and one-to-one privates. The current four-week session runs Tuesdays and
  Thursdays. The wading pool teaches three classes at once, side by side.</p>
{BAY_TABLE}
{cal("bays", "Learn-to-swim bays — Clarke Wading Pool", short=True,
     caption="Classes run late afternoon &mdash; scroll to 4:30pm, or tap <strong>LIST</strong>.")}
</section>

<section class="wrap" id="rentals">
  <h2>Recreational swim, water exercise and rentals</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>What</th><th>When</th><th>Notes</th></tr></thead>
    <tbody>
      <tr><td>Recreational swim</td><td>Weekends, 12:00&ndash;5:00 pm</td><td>Rest break 2:40&ndash;3:00. Adult $8 / Youth 7&ndash;17 $7 / Child 0&ndash;6 $6</td></tr>
      <tr><td>Inflatable obstacle courses</td><td>Summer rec-swim hours</td><td>$3 Splash Pass on top of admission; staffing and heat permitting</td></tr>
      <tr><td>Water exercise</td><td>Tue, Wed, Thu &mdash; 8:15 shallow, 9:15 deep</td><td><strong>Not currently running</strong> &mdash; the city is looking for an instructor</td></tr>
      <tr><td>South Patio picnic rental</td><td>Weekends, 11 April &ndash; 27 September</td><td>5 tables, BBQ, refrigerator. Up to 60 guests. $200 spring/fall, $300 summer</td></tr>
      <tr><td>Pavilion rental</td><td>Summer weekends, 13 June &ndash; 9 August</td><td>4 tables under shade, up to 40 guests. $250</td></tr>
    </tbody>
  </table>
  </div>
  <div class="note">
    <span class="hd">Water exercise is on the page but not on the calendar</span>
    The city lists the times and then says it has no instructor. A calendar entry would hold that water
    whatever its description said, so the slots were deliberately left off. If the water is still being
    reserved for the class, it should go on &mdash; that is one of the questions below.
  </div>
</section>

{QUESTIONS}"""

# ══ 3. Larkey ═════════════════════════════════════════════════════════════════
LARKEY = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Swim Centers</div>
  <h1>Larkey Swim Center</h1>
  <p class="kicker">Summer only &middot; closed until Memorial Day</p>
  <p class="lead">A 25&times;25 meter heated pool with a one-meter diving board, and an accessible
  all-abilities sprayground with slides and waterfalls. 2771 Buena Vista Ave, Walnut Creek.
  Front desk (925)&nbsp;943-5861.</p>

{cal("larkey", "Larkey Swim Center — the season, month by month",
     caption="Shown a month at a time. September is the season ending: weekday sprayground hours, then the last weekends, then the Labor Day opening.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The season ends on a date, not on somebody remembering</h2>
    <p>Larkey closed after Labor Day and its calendar closed with it, because the whole season was
    entered as <b>dates</b> rather than as a sentence on a web page.</p>
    <p>Nobody has to go back in September and edit <i>&ldquo;open weekends only through 9/7&rdquo;</i>
    off the site. Nobody has to retype the summer next May. Recreational swim, the $3 sprayground
    hours, the picnic rentals and the private sprayground hour are already in place, waiting for the
    season to come round.</p>
    <p class="answer">Page the calendar back to July and the whole summer is there exactly as it ran
    &mdash; <b>which also means next season can be edited now, in February, instead of in a rush in
    May.</b></p>
  </div>
</div>

<section class="wrap" id="passes">
  <h2>The summer week</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>What</th><th>When</th><th>Where</th></tr></thead>
    <tbody>
      <tr><td>Recreational swim &amp; sprayground</td><td>Sat &amp; Sun, 12:00&ndash;5:00 pm <span style="color:var(--muted)">(rest break 2:40&ndash;3:00)</span></td><td>Main Pool + Sprayground</td></tr>
      <tr><td>Sprayground only &mdash; $3</td><td>Mon&ndash;Thu, 10:30 am&ndash;12:30 pm and 4:30&ndash;6:30 pm</td><td>Sprayground</td></tr>
      <tr><td>Picnic rentals</td><td>Summer weekends, 13 June &ndash; 9 August</td><td>Picnic Area</td></tr>
      <tr><td>Private sprayground rental</td><td>Summer weekends, 10:30&ndash;11:30 am</td><td>Sprayground &mdash; closed to everyone else</td></tr>
      <tr><td>Labor Day opening</td><td>Monday 7 September, 12:00&ndash;5:00 pm</td><td>Main Pool + Sprayground</td></tr>
    </tbody>
  </table>
  </div>

  <h2 style="margin-top:34px">Admission</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Who</th><th>Price</th></tr></thead>
    <tbody>
      <tr><td>Adult (18+)</td><td class="n">$8</td></tr>
      <tr><td>Youth (7&ndash;17)</td><td class="n">$7</td></tr>
      <tr><td>Child (0&ndash;6)</td><td class="n">$6</td></tr>
      <tr><td>Sprayground-only hours</td><td class="n">$3</td></tr>
    </tbody>
  </table>
  </div>
  <p class="capt">The Summer Recreational Swim Pass covers rec-swim hours at <em>both</em> centers,
  Memorial Day through Labor Day. It does not cover the $3 inflatable fee at Clarke, and it is not
  valid for lap swim or water exercise.</p>

  <div class="note">
    <span class="hd">One thing we had to guess</span>
    The $3 weekday sprayground hours are published without any dates. We used the Memorial
    Day&ndash;Labor Day season the swim pass names, stopping the Thursday before Labor Day because the
    center had already gone to weekends only by September. The real weekday season is the aquatics
    office's to confirm.
  </div>
</section>

"""

# ══ 4. Aquabears ══════════════════════════════════════════════════════════════
AQUABEARS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Competitive Swim Teams</div>
  <h1>Walnut Creek Aquabears</h1>
  <p class="kicker">Year-round USA Swimming &middot; eight practice groups &middot; daily at Clarke</p>
  <p class="lead">The nationally ranked Aquabears are a year-round competitive program. Head coach
  Mike Heaney, (925)&nbsp;939-5990. The team practices daily at Clarke Memorial Swim Center in Heather
  Farm Park.</p>

{cal("clarke", "Clarke Memorial Swim Center — this week",
     caption="Clarke's published week. Every block here is somebody else's.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Eight groups, in the water daily, on no public schedule</h2>
    <p>The calendar above is everything Clarke publishes: lap swim, Masters, lessons, weekend
    recreation. It is complete, and the Aquabears are <b>not in it</b> &mdash; not because they are not
    there, but because their practice times are behind a member login.</p>
    <p>The team's own progression chart says what the commitment is. Each group is offered five to
    eight practices a week, of sixty to a hundred and twenty minutes, every one of them in Clarke
    water that the city is simultaneously publishing as a lane count.</p>
    <p class="answer">Put the eight groups on the same calendar and three things become true at once:
    <b>a parent sees which lanes their swimmer is in, the city sees what its pool is actually
    committed to, and lap swimmers stop guessing</b> which twelve lanes are gone this afternoon.</p>
  </div>
</div>

<section class="wrap">
  <h2>The practice groups</h2>
  <p>From the team's own <em>Progression through the Practice Groups</em> chart.</p>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Group</th><th>Swimmers</th><th>Practice commitment</th></tr></thead>
    <tbody>
      <tr><td>Purple 1</td><td>New to the sport, 8&ndash;11, with lesson experience</td><td>At least 3 of 5 &times; 60 minutes</td></tr>
      <tr><td>Purple 2</td><td>8&ndash;10, with team experience</td><td>At least 3 of 5 &times; 60 minutes</td></tr>
      <tr><td>Purple 3</td><td>8&ndash;10, with team experience</td><td>At least 4 of 6 &times; 60 minutes</td></tr>
      <tr><td>Gold 1</td><td>11 through 8th grade</td><td>At least 3 of 5 &times; 60 minutes</td></tr>
      <tr><td>Gold 2</td><td>11 through 8th grade</td><td>At least 4 of 6 &times; 90 minutes</td></tr>
      <tr><td>Gold 3</td><td>11 through 8th grade</td><td>At least 4 of 6 &times; 90 minutes</td></tr>
      <tr><td>Senior 1</td><td>9th grade and above</td><td>At least 5 of 8 &times; 120 minutes</td></tr>
      <tr><td>Senior 2</td><td>9th grade and above</td><td>At least 6 of 8 &times; 120 minutes</td></tr>
    </tbody>
  </table>
  </div>
  <p class="capt">Swimmers move up on age, on completing a group, or on coach recommendation after
  qualifying times &mdash; the chart maps every route.</p>

  <div class="note">
    <span class="hd">What is missing, and where it would go</span>
    Group names, ages and practice counts are public. <strong>Clock times and lane assignments are
    not.</strong> Those are exactly what the calendar above is shaped to hold: each group is already
    set up in Pool Relay, waiting for its times.
  </div>

  <p><a href="https://www.gomotionapp.com/team/wcab/page/home" target="_blank" rel="noopener">Walnut Creek Aquabears website &rarr;</a></p>
</section>

"""

# ══ 5. Masters ════════════════════════════════════════════════════════════════
MASTERS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Competitive Swim Teams</div>
  <h1>Walnut Creek Masters</h1>
  <p class="kicker">Ages 19&ndash;90 &middot; thirteen practices a week &middot; Clarke 50-meter pool</p>
  <p class="lead">A competitive swimming program and a structured fitness program for adults of all
  abilities. Head coaches Mike Heaney and Steve Stahl, (925)&nbsp;280-5421.</p>

{cal("masters", "Walnut Creek Masters — the practice week",
     caption="Thirteen practices a week, every one in the Clarke 50-meter pool.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>The team that completes the city's own lane table</h2>
    <p>Masters is the one Walnut Creek team that publishes its practice times, and putting them beside
    the city's published lane counts is what makes both make sense. The city says how many lanes are
    public; the team says when it is training. Together they account for the pool exactly.</p>
{LANE_TABLE.replace('  <div class="scroller">', '  <div class="scroller" style="background:#fff;border-radius:4px;padding:2px">')}
    <p class="answer">Every weekday band adds to twenty. <b>That agreement is evidence</b> &mdash; two
    organizations, two websites, no coordination, one pool that adds up.</p>
  </div>
</div>

<section class="wrap">
  <h2>Practice times</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Monday, Wednesday, Friday</th><th>Tuesday, Thursday</th><th>Saturday</th></tr></thead>
    <tbody>
      <tr><td>5:30 &ndash; 6:20 am</td><td>5:30 &ndash; 6:40 am</td><td>9:30 &ndash; 10:45 am</td></tr>
      <tr><td>6:20 &ndash; 7:10 am</td><td>6:50 &ndash; 8:00 am</td><td></td></tr>
      <tr><td>7:10 &ndash; 8:00 am</td><td>10:30 &ndash; 11:40 am</td><td></td></tr>
      <tr><td>10:30 &ndash; 11:20 am</td><td>11:50 am &ndash; 1:00 pm</td><td></td></tr>
      <tr><td>11:20 am &ndash; 12:10 pm</td><td>7:00 &ndash; 8:00 pm</td><td></td></tr>
      <tr><td>12:10 &ndash; 1:00 pm</td><td></td><td></td></tr>
      <tr><td>7:00 &ndash; 8:00 pm <span style="color:var(--muted)">(not Fridays)</span></td><td></td><td></td></tr>
    </tbody>
  </table>
  </div>

  <div class="note">
    <span class="hd">The lane count on these entries is ours, not the team's</span>
    Masters publishes times but never lanes. We entered twelve &mdash; the balance of the twenty-lane
    short course after the city's published public allocation. It closes perfectly in every weekday
    band, which is good evidence but not confirmation. The Saturday 9:30&ndash;10:45 practice has no
    published allocation to bound it at all, so that one is a straight guess.
  </div>

  <p><a href="https://www.swim4wc.org/page/home" target="_blank" rel="noopener">Walnut Creek Masters website &rarr;</a></p>
</section>

"""

# ══ 6. Aquanuts ═══════════════════════════════════════════════════════════════
AQUANUTS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Competitive Swim Teams</div>
  <h1>Walnut Creek Aquanuts</h1>
  <p class="kicker">Synchronized swimming &middot; year round &middot; the 25-meter pool</p>
  <p class="lead">One of the most acclaimed teams in international synchronized swimming, and home of
  Olympic champions. A year-round program for swimmers of all ages and abilities. Head coach Kim
  Probst, (925)&nbsp;934-4792.</p>

{cal("pool25", "Clarke 25-Meter Pool — the public week", short=True,
     caption="The 25-meter pool as the public can currently see it.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>A pool held year round, and a week that shows two weekend afternoons</h2>
    <p>The city's own description of Clarke says the 25-meter pool <i>&ldquo;is used year-round for
    synchronized swim practice.&rdquo;</i> The calendar above is everything that pool currently
    publishes: recreational swim at the weekend, and nothing else.</p>
    <p>That gap is not a mistake in the calendar. It is an accurate picture of what Walnut Creek
    publishes about a pool that one of the most decorated synchro programs in the world trains in
    every week of the year.</p>
    <p class="answer">For the Aquanuts the argument is simple: <b>a pool you hold year round should
    look held.</b> Families planning around practice, the city planning around rentals, and anyone
    wondering whether the 25-meter pool is free on a Wednesday are all currently guessing.</p>
  </div>
</div>

<section class="wrap">
  <h2>What is already set up</h2>
  <p>The Aquanuts exist in Pool Relay as their own organization, and the 25-meter pool exists as its
  own water at Clarke. Practice times are the only missing piece &mdash; the team publishes none, and
  its website could not be read at all when this page was built.</p>

  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Known</th><th>Not published anywhere</th></tr></thead>
    <tbody>
      <tr><td>Year-round use of the Clarke 25-meter pool</td><td>Practice days and times</td></tr>
      <tr><td>All ages and abilities</td><td>How the squad divides into groups</td></tr>
      <tr><td>Head coach Kim Probst</td><td>Which part of the pool each group uses</td></tr>
      <tr><td>Summer sharing with lessons and rec swim</td><td>How the summer overlap is handled</td></tr>
    </tbody>
  </table>
  </div>

  <p><a href="https://www.teamunify.com/team/reczzwca/page/home" target="_blank" rel="noopener">Walnut Creek Aquanuts website &rarr;</a></p>
</section>

"""

# ══ 7. Walnut Creek Swim Club ═════════════════════════════════════════════════
WCSC = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Aquatics</a> &raquo; Competitive Swim Teams</div>
  <h1>Walnut Creek Swim Club</h1>
  <p class="kicker">Summer recreational swim team &middot; 55th year</p>
  <p class="lead">One of the oldest and finest recreational swim teams in the county, built around
  swimmers improving and families having a good summer. Contact
  <a href="mailto:director@walnutcreekswimclub.org">director@walnutcreekswimclub.org</a>.</p>

{cal("hub", "Walnut Creek Aquatics — everything, both swim centers",
     caption="Both centers, this week. WCSC is a summer team, so its season sits outside this window entirely.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>A summer team, and a summer that has to be rebuilt every year</h2>
    <p>WCSC runs in the season when Walnut Creek aquatics is busiest: rec swim at both centers, the
    sprayground open on weekday mornings, picnic rentals every weekend, lessons in three bays at once,
    and two year-round teams still training through it.</p>
    <p>None of that is coordinated in one place today. The city publishes its part, the teams publish
    theirs, and the summer is reassembled by hand every May.</p>
    <p class="answer">A season entered once is a season that comes back on its own. <b>The Larkey
    summer is already sitting in the calendar waiting for Memorial Day</b> &mdash; a swim club's season
    can sit there the same way, alongside the water it shares.</p>
  </div>
</div>

<section class="wrap">
  <h2>What the summer looks like around a rec team</h2>
  <div class="scroller">
  <table class="sched">
    <thead><tr><th>Also in the water, Memorial Day to Labor Day</th><th>When</th></tr></thead>
    <tbody>
      <tr><td>Recreational swim, both centers</td><td>Weekends, 12:00&ndash;5:00 pm</td></tr>
      <tr><td>Larkey sprayground-only hours</td><td>Mon&ndash;Thu, 10:30&ndash;12:30 and 4:30&ndash;6:30</td></tr>
      <tr><td>Swim lessons at Clarke</td><td>Four-week sessions, afternoons and Saturday mornings</td></tr>
      <tr><td>Masters practice</td><td>Thirteen times a week, year round</td></tr>
      <tr><td>Aquanuts synchro</td><td>Year round, 25-meter pool</td></tr>
      <tr><td>Picnic and pavilion rentals</td><td>Weekends, 13 June &ndash; 9 August</td></tr>
    </tbody>
  </table>
  </div>

  <div class="note">
    <span class="hd">The one thing nobody publishes</span>
    Of the four teams, WCSC is the only one whose <strong>venue</strong> is not stated anywhere on the
    city's site &mdash; not just its practice times. That is the first question for the club, and the
    reason this page shows both centers rather than picking one.
  </div>

  <p><a href="http://www.walnutcreekswimclub.org/" target="_blank" rel="noopener">Walnut Creek Swim Club website &rarr;</a></p>
</section>

"""

PAGES = [
    ("index.html", "Aquatics &mdash; Walnut Creek Arts + Rec (Pool Relay preview)",
     "Unofficial preview of the Walnut Creek aquatics page with one live Pool Relay calendar covering both swim centers and every program.", HUB),
    ("clarke.html", "Clarke Memorial Swim Center &mdash; Walnut Creek Arts + Rec (Pool Relay preview)",
     "Unofficial preview: Clarke Memorial Swim Center with a live lane calendar for all three pools.", CLARKE),
    ("larkey.html", "Larkey Swim Center &mdash; Walnut Creek Arts + Rec (Pool Relay preview)",
     "Unofficial preview: Larkey Swim Center, a summer pool whose season is entered as dates.", LARKEY),
    ("aquabears.html", "Walnut Creek Aquabears &mdash; Pool Relay preview",
     "Unofficial preview: the Aquabears, eight practice groups training daily at Clarke.", AQUABEARS),
    ("masters.html", "Walnut Creek Masters &mdash; Pool Relay preview",
     "Unofficial preview: Walnut Creek Masters, thirteen practices a week in the Clarke 50-meter pool.", MASTERS),
    ("aquanuts.html", "Walnut Creek Aquanuts &mdash; Pool Relay preview",
     "Unofficial preview: the Aquanuts, holding the Clarke 25-meter pool year round for synchronized swimming.", AQUANUTS),
    ("wcsc.html", "Walnut Creek Swim Club &mdash; Pool Relay preview",
     "Unofficial preview: Walnut Creek Swim Club, a summer recreational swim team in its 55th year.", WCSC),
]


def main():
    for slug, title, description, body in PAGES:
        html = shell(slug, title, description, body)
        with io.open(os.path.join(HERE, slug), "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"wrote {slug} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
